### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by dionysio** [machrisaa/stylenet#1]
Hey, so I started using your code and I have encountered quite high memory usage. I have GPU-enabled Tensorflow, CUDA works well and it stays around 2.5GB in GPU memory for the default settings. My issue is with RAM - it keeps rising up to around 9GB. Is this normal behaviour or is there something wrong with my Tensorflow installation? Do you have maybe some tips for other settings I might use in your code?

Thanks

**Comment by machrisaa** [comment]
Hi, I am afraid it may be some problem about your Tensorflow installation or you hardware. I have just tested running the stylenet_patch.py and it used ~3.3GB memory and consumed at most 1GB GPU memory. I have captured the result for your reference:

<img width="402" alt="screen shot 2016-04-08 at 13 33 39" src="https://cloud.githubusercontent.com/assets/12701396/14383759/fe178000-fd8e-11e5-9581-747cc81f5c55.png">

[log.txt](https://github.com/machrisaa/stylenet/files/210143/log.txt)

I think i can justify the 3.3GB. We used 3 VGG19 net for the rendering and they with consume about 1.8GB memory. In addition to the overhead from Tensorflow, and the numpy patch generation, it think <4GB memory consumption is expected.

As for the GPU memory, i have already tune the running setting by using 0.7 of total memory:
`gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
    with tf.Session(config=tf.ConfigProto(gpu_options=(gpu_options), log_device_placement=False)) as sess:`
And I have tested for some bigger images (around 800px \* 630px) on my Macbook pro with 2GB GPU memory. This setting should be fine.
