### ISSUE TITLE
A question about the MRF implementation in the code

### ISSUE THREAD

**Issue by NoNamesLeft4Me** [machrisaa/stylenet#4]
I am trying to understand the MRF paper and after I read your code, one part confuses me a little bit, which is `get_style_cost_patch2()` in stylenet_core.py. I am wondering if you could help me out?

From my understanding, function `get_style_cost_patch2()` is trying to calculate MRF cost, defined as Eq. (2) in the paper. And within it, calculating Eq.(3) is done by this line of code:
`max_arg_out, patches = _create_patch(sess, content_input, style_input, content_regions, style_regions, blur_mapping)`
It seems that this line of code finds the maximized matching patches between the style image and the content image. However in the paper, Eq (3) aims to find the maximized matching patches between the style image and the synthesized image. 

I am wondering if I miss something from your implementation, or you modify the algorithm on purpose?

I also tried to modify this part back according to the paper and write a simply modified function `get_style_cost_patch()`. However TF reports an error saying Attempting to use uninitialized value Variable. I am wondering if you have some insight about why the error happens? Thanks,
My modified code is below:

```
def get_style_cost_patch(sess, var_input, style_input, save_file,
                          content_regions=None, style_regions=None,
                          load_saved_mapping=True, blur_mapping=False):
    dim = var_input.get_shape().as_list()
    h, w, d = dim[1], dim[2], dim[3]
    ph, pw = h - 2, w - 2
    pn = ph * pw
    full_patch_file = save_file + "_full.npy"

    full_patch_out = None
    if load_saved_mapping:
        try:
            full_patch_out = np.load(full_patch_file)
        except:
            print("saved full patch not found")
    if full_patch_out is None:
        with tf.device("/cpu:0"):
            max_arg_out, patches = _create_patch(sess, var_input, style_input,
                                                 content_regions, style_regions, blur_mapping)
            assert patches.get_shape().as_list() == [3, 3, d, pn]

            max_arg_out = np.reshape(max_arg_out, [ph, pw])
            # print max_arg_out
            full_patch = _join_patches_np(sess, patches, max_arg_out)

            assert full_patch.get_shape() == var_input.get_shape()
            full_patch_out = sess.run(full_patch)
            np.save(full_patch_file, full_patch_out)

    full_patch = tf.constant(full_patch_out)

    cost = l2_norm_cost(var_input - full_patch)

    return cost
```

**Comment by machrisaa** [comment]
Hi @NoNamesLeft4Me, good catch! Never did anyone ask me about the idea behind this. Well, yes, I did it on purpose. Base on my understanding, the paper search for the nearest patch in each step of training (Correct me if I am wrong). But this calculation is extremely slow. Therefore, in my implementation, I changed it to search 1 time only and that is when the first step of the training. 

In the source code, you can see that only when `full_patch_out is None` the searching will be executed in this line `full_patch_out = sess.run(full_patch)`. The result is a narray and it will be converted into the constant tensor `full_patch = tf.constant(full_patch_out)`. Unlike those tensor which depends on the inputs, this constant tensor only has the constant value and will not be updated throughout the training. Therefore, the nearest patch searching has only be done a single time in this implementation.

So the answer to your question is that there is no need to use `var_input` to search for the nearest patch in this implementation. My implementation of the patch searching is "static" (only depends on the initial input) but not "dynamic" (based on the changed image in each step).

Of course, you can change your code to be "dynamic" if you have a very nice machine to render the graphs. But your code also needs to change a little bit more to do so.

The next question is what is the difference between "static" and "dynamic" patch searching? My experience is that "static" patch search works but not as good as dynamic search. Therefore, in the `stylenet_patch.py`, I added the method `render_gen` in which it "re-search" the nearest patch after certain iterations of training. And I call each "re-searching" a generation. It will usually generate a better result comparing with the original method.

You can try it yourself by uncomment and run [#338](https://github.com/machrisaa/stylenet/blob/master/stylenet_patch.py#L338) to see the difference.

**Comment by NoNamesLeft4Me** [comment]
Thanks for your explanation! @machrisaa 
I am trying `render_gen ` now. I thought it is for the multi-resolution process, and I didn't relate it to the "static" patch searching.

I have two follow-up questions and wonder if you could help me out.
The first one is that for your "static" implementation, when you calculate the matching patches in the first time, do you assume the synthesized image is initialized with content image? In the code, when `full_patch_out is None`, the patches are obtained by the line of code:
```
            max_arg_out, patches = _create_patch(sess, content_input, style_input,
                                                 content_regions, style_regions, blur_mapping)
```
This implies that `content_input ` has the same value as `var_input `at the first run? If `random_init `is True, this assumption might be broken.

The second one is about the "dynamic" patch-matching. I encounter an error when I tried to implement it based on your code. Without considering any efficiency, what I tried is to simply replace `content_input `with `var_input `in the line above, so it becomes: 
```
            max_arg_out, patches = _create_patch(sess, var_input, style_input,
                                                 content_regions, style_regions, blur_mapping)
```
However TF reports an error of `Attempting to use uninitialized value Variable`. I guess the error happens because TF doesn't figure out the dependency of variables, but I am not sure how to fix this. You mention I need to change a little bit more to do so. Could you elaborate a little more on this, or do you have any insight how to fix this error? Thanks!

**Comment by NoNamesLeft4Me** [comment]
@machrisaa 
I find out why this simple modification doesn't work for the "dynamic" patch-matching. `var_input` cannot be directly fed into the function `_create_patch`. Since `var_input` is a tf variable, I have to modify `_create_patch` and `_slice_patches_np(sess, v)` to avoid using sess.run() on `var_input` related variables.

**Comment by machrisaa** [comment]
Hi @NoNamesLeft4Me, for your second question, basically you are right. I used few times of `sess.run` to make the results become constants since those results will not be changed in the "static" mode calculation.

As for your first question, `content_input` and `var_input` can be totally different in the static calculation because the `_create_patch` function is to find the most similar patch in the `style_input` for each patch of the `content_input`. Therefore, using `var_input` in this function do not make any sense in static mode if the `var_input` initialised randomly.

However, if you want to implement the dynamic patch searching, you have to put `var_input` in this function because you need to patch search to be executed in each step of your training. In this case, you must initialise the `var_input` to make the patch searching meaning in each step.

If you want to change the search mode, I have two remarks for you.

The first thing is, to be honest, I am not very sure if the author of the paper really want the patch searching running dynamically. And I guess you may not have significantly better result if you do the searching too frequently.

The second thing is that this project was done in the early version of Tensorflow. At that moment, there are no native functions to handle image patches. But I notice that they have created the [tf.extract_image_patches](https://www.tensorflow.org/api_docs/python/tf/extract_image_patches)  couple of months ago. Although I haven't tried to use it, it should have much better performance than using slicing and stitching in my implementation.

**Comment by NoNamesLeft4Me** [comment]
Hi @machrisaa Thanks for your advice!
Maybe I miss something from the paper, but Eq(2) and Eq(3) in the paper indicate to find matching patches between the style image and the synthesized image and use it as the style cost term. Maybe that's only the theoretical proposal and the authors implement a more practical method like yours. I will check their original Torch implementation to confirm it.

As it is, I implemented the dynamic patch searching. You suggestion with tf.extract_image_patches really helps a lot. I just finished the implementation and ran the example of the cat image and a tiger image. 

![cat_h](https://cloud.githubusercontent.com/assets/24922424/25243684/c5eadd24-25b2-11e7-9e8b-637770a17d79.jpg)

![tiger](https://cloud.githubusercontent.com/assets/24922424/25243710/dcb38920-25b2-11e7-88d5-8e97427730d6.jpeg)

For the simplest test, I use the cat as the content image, and the tiger as the style image. I only use the MRF conv3_1 term, and turn off all other cost terms and the initial image is random Gaussian noise. The difference between results of the dynamic and static ones are quite different. The first one is the static and the second one is the dynamic one. I think the static one merges the texture of the style image with the content image. Yet, the dynamic one captures only the "texture" part of the style image. However, for the ultimate effects of style transfer when combining other terms, I think maybe the difference is not big, as you assume.

![output500](https://cloud.githubusercontent.com/assets/24922424/25243900/8c8c03b8-25b3-11e7-8409-ebfb845d6792.jpg)
![output500](https://cloud.githubusercontent.com/assets/24922424/25243911/941c2ba8-25b3-11e7-85df-058ed5c56be3.jpg)

Another thing is the running time. The dynamic one is super slow. For 500 epochs, it ran 1108 sec on the above case, compared to 49 sec for static one. Beside the actual calculation, one problem is that I can't find any native functions to convert patches with max indexes back to the image tensor (the `_join_patches_np` function in your implementation), so I use numpy to do the work which might slow things down. If a faster implementation is not available, I will reduce the patches number and maybe reduce the patch-search frequency to speed up a little bit.

Thanks for your help on this matter, I will keep you update when I have some processes, if you would like to.

**Comment by machrisaa** [comment]
Thanks for sharing your result and it is very interesting. Did you tried to initialise the synthesized image with the content image in the dynamic method? It should improve the searching in the begining stage of the training and fix the problem of unable to transfer the content.

**Comment by NoNamesLeft4Me** [comment]
Yes, I tried to initialize the synthesized image with the content image, for both static and dynamic search. The first one below is from static search. The second one is from dynamic search.
![output500](https://cloud.githubusercontent.com/assets/24922424/25349058/484f05cc-28d5-11e7-8874-446c73e40ddb.jpg)
![output400](https://cloud.githubusercontent.com/assets/24922424/25349078/586be15a-28d5-11e7-964c-89018fae9fae.jpg)

I think for static search, the results are the same with these two initialization. The results preserve both the content information and texture information. For dynamic search, the results varies, due to different initialization. And the results are an extraction of texture with the content of the initialization.

For my purpose, I want to find out the best method to synthesize texture, so I am more interested in the dynamic search because it seems to be more effective.

Besides, I manage to reduce the running time by not pinning the operation on CPU by `removing with tf.device("/cpu:0"):` in `def get_style_cost_patch2()`. I find out this actually speed up the training, i.e. for the above case, it ran 271 sec, compared to previous 1108 sec. However this implementation really consumes a lot of power. It goes to OOM when I tried to run on a style image of 600x400.

**Comment by machrisaa** [comment]
Well done @NoNamesLeft4Me! The one initialised with the content image with the dynamic search is better than your last result. 

However, as shown in your second result, the content is not fully transferred. Unfortunately, I think this is a problem about the algorithm that cannot be avoided. One major limitation of the algorithm is that it finds the most similar patches from the style image only by finding the cross-correlations between patches. There is no rotation nor enlargement in the searching algorithm. Like the example, you have, a cat and a tiger, the eye of the tiger cannot be transferred to the patch of the eye of the cat because their scale is different.

So if the content image and the style image have very similar colour tone, scale, and orientation, like the husky sample in the project, the result would be better.
